name: Deploy Mkdocs Site

on:
  push:
    branches:
      - main
concurrency:
  group: deployment

jobs:
  Run-Code-Validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --only docs
      - name: Deploy Site
        run: poetry run mkdocs gh-deploy --force --clean
